"""Migration 1751391719432

Revision ID: 000ec5a7e1c1
Revises: cbab847f6a7d
Create Date: 2025-07-01 21:43:22.003208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000ec5a7e1c1'
down_revision = 'cbab847f6a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
