"""Migration 1753551905148

Revision ID: 2b1397188a14
Revises: 6edbc6b3cba8
Create Date: 2025-07-26 21:46:17.334540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1397188a14'
down_revision = '6edbc6b3cba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('visitor_log_ip_address_key', type_='unique')
        batch_op.create_unique_constraint(None, ['visitor_id'])
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('visitor_log_ip_address_key', ['ip_address'])
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###
