"""Migration 1752351674710

Revision ID: 31a14bbf6e9f
Revises: cc5b1053de5e
Create Date: 2025-07-13 00:23:05.452238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a14bbf6e9f'
down_revision = 'cc5b1053de5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('area', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('area')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
