"""Migration 1752602607180

Revision ID: 4f9235801fe2
Revises: 31a14bbf6e9f
Create Date: 2025-07-15 22:06:08.068571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f9235801fe2'
down_revision = '31a14bbf6e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_size_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='cart_item_product_id_fkey'),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_size.id'], name='cart_item_product_size_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='cart_item_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_item_pkey')
    )
    # ### end Alembic commands ###
