"""Migration 1751395317477

Revision ID: 527c2044e8c6
Revises: 000ec5a7e1c1
Create Date: 2025-07-01 22:43:33.687662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527c2044e8c6'
down_revision = '000ec5a7e1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('length_cm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('width_cm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('delivery_factor', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.drop_column('delivery_factor')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('width_cm')
        batch_op.drop_column('length_cm')
        batch_op.drop_column('weight_kg')

    # ### end Alembic commands ###
