"""Migration 1750872911595

Revision ID: 69c464a972f7
Revises: 
Create Date: 2025-06-25 21:35:53.017091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c464a972f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_size_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product_size', ['product_size_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_size_id')

    # ### end Alembic commands ###
