"""Migration 1753549795181

Revision ID: 6edbc6b3cba8
Revises: 4f9235801fe2
Create Date: 2025-07-26 21:11:23.335327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edbc6b3cba8'
down_revision = '4f9235801fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_index('ix_visitorlog_last_seen_ip')
        batch_op.create_index('ix_visitorlog_last_seen', ['last_seen'], unique=False)
        batch_op.create_unique_constraint(None, ['ip_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_visitorlog_last_seen')
        batch_op.create_index('ix_visitorlog_last_seen_ip', ['last_seen', 'ip_address'], unique=False)

    # ### end Alembic commands ###
