"""Migration 1751118009326

Revision ID: bfcbb1475139
Revises: 69c464a972f7
Create Date: 2025-06-28 17:40:51.215606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcbb1475139'
down_revision = '69c464a972f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.drop_column('available_quantity')

    # ### end Alembic commands ###
