"""Migration 1751720237715

Revision ID: ddbd6f539e78
Revises: fec9a6d07320
Create Date: 2025-07-05 16:58:36.932783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddbd6f539e78'
down_revision = 'fec9a6d07320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failed_transaction', schema=None) as batch_op:
        batch_op.drop_column('payment_sub_type')
        batch_op.drop_column('currency')
        batch_op.drop_column('is_refunded')
        batch_op.drop_column('payment_type')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('txn_response_code')
        batch_op.drop_column('is_voided')
        batch_op.drop_column('error_reason')
        batch_op.drop_column('is_settled')
        batch_op.drop_column('error_occured')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failed_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_occured', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_settled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('error_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_voided', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('txn_response_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_refunded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_sub_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
