"""Migration 1751805679507

Revision ID: e58dce425491
Revises: 5fbfdb80ebcb
Create Date: 2025-07-06 16:42:26.859731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58dce425491'
down_revision = '5fbfdb80ebcb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('is_3d_secure',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('payment_sub_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('is_voided',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_refunded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_settled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('refunded_amount_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('captured_amount_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('error_occured',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('error_occured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('captured_amount_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('refunded_amount_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_settled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_refunded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_voided',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('payment_sub_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('is_3d_secure',
               existing_type=sa.BOOLEAN(),
               nullable=True)


    # ### end Alembic commands ###
