"""Phase C & G

Revision ID: ebdea9e30d11
Revises: 42ab09e0a9b1
Create Date: 2026-05-04 20:11:18.213675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdea9e30d11'
down_revision = '42ab09e0a9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.Float(), server_default='0.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')

    # ### end Alembic commands ###
